---
title: "CAWC Origins, Languages & Destinations Report"
author: "Kendra Lyons"
date: "3/11/2022"
output: 
  html_document:
    toc: true
---

```{r setup, include=FALSE}
library(ggrepel)
library(knitr)
library(tidyverse)
library(scales)
library(usmap)
opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

## Data Dates: 1/26/21 to 1/20/22

Data for this project were collected by volunteers and staff at Casa Alitas Welcome Center in Tucson, Arizona. 

```{r data, include = FALSE}

individuals <- read_csv("data/individual_all_clean_1_20_22.csv", na = c("", "NA")) %>% 
  rename("GroupID" = ...1) %>%
  select(arrival_date, GroupID, language, country, state_name, state_abb)

countries <- drop_na(read_csv("data/country_counts_1.20.csv"))

languages <- drop_na(read_csv("data/language_counts_1.20.csv"))

destinations <- drop_na(read_csv("data/destination_counts_1.20.csv"))

# Add values of 0 for states with no travelers
destinations <- destinations %>%
  add_row(state_name = "Hawaii", n = 0, percent = 0.0) %>%
  add_row(state_name = "North Dakota", n = 0, percent = 0.0) %>%
  add_row(state_name = "Wyoming", n = 0, percent = 0.0) %>%
  rename("state" = state_name)

# get state centroids for labels
centroids <- read_csv("data/us_states_centroids.csv") %>%
  rename("state" = full)

# add centroid data to destination data 
map_destinations <- centroids %>%
  left_join(destinations)

# get immigration policy event data 
policy_events <- read_csv("data/migration_policy_events_timeline_2021_selected.csv", skip = 2) %>%
  mutate(date = parse_date(date, format = "%m/%d/%Y"),
         category = category)

# select events of interest
key_policy_events <- policy_events %>%
  filter(category %in% c('MPP ("Remain in Mexico")', 
                         'Title 42', 
                         'Temporary Protected Status')) #, 'Detention'

```

## Languages

```{r languages, echo=FALSE}
# set plot theme
theme_set(theme_minimal(14))

# plot arrivals of other language speakers over time
some_langs = languages$language[languages$n > 4]

individuals %>%
  filter(language %in% some_langs) %>%
  ggplot(aes(x = arrival_date, 
             y = factor(language, rev(some_langs)))) +
  geom_point(alpha = .2) +
  labs(title = "Arrivals over time by language spoken",
       x = element_blank(), 
       y = element_blank()) +
  scale_x_date(date_breaks = "1 month", 
               date_labels = "%b",
               expand = c(.02,-.02)) 
  
```

## Countries of Origin

```{r orig_fw, echo=FALSE}
 # filter out countries with few arrivals
top_ctrys <-  countries$country[0:12]
# Top 12 countries of origin FW 
individuals %>%
  filter(country %in% top_ctrys) %>%
  ggplot(aes(x = arrival_date)) +
  geom_bar(show.legend = FALSE) +
  labs(title = "Daily arrivals over time, top origin countries", 
       x = element_blank(), 
       y = "Number of Individuals") + 
  facet_wrap(~factor(country, top_ctrys), 
             scales = "free_y")  +
  scale_x_date(date_breaks = "3 month", 
               date_labels = "%b",
               expand = c(.02,-.02))
```

```{r orig_policy, echo=FALSE}
# get countries with arrivals greater than 100
some_ctrys <- countries$country[countries$n > 100]
# Arrivals by country over time dot plot
individuals %>%
  filter(country %in% some_ctrys) %>%
  ggplot(aes(x = arrival_date, 
             y = factor(country, rev(countries$country[1:23])))) +
  geom_vline(data = key_policy_events, 
             aes(xintercept = date, 
                 color = category),
             na.rm = TRUE,
             size = .75) +
  geom_point(alpha=.2) +
  theme(legend.position = "top", 
        legend.justification = 0) +
  scale_color_manual(values = c("purple", "orange", "darkgreen")) +
  labs(title = "Policy change effects by origin country",
       x = element_blank(), 
       y = element_blank(),
       color = element_blank()) +
  scale_x_date(date_breaks = "1 month", 
               date_labels = "%b",
               expand = c(.02,-.02)) 

# print table with policy change details
key_policy_events %>%
  kable(caption = "Immigration Policy Changes in 2021 (Source: Investigative Reporting Workshop)")

```

## Destination States

```{r destorig, echo=FALSE}
# get top destination states
top_states <- destinations$state[1:12]
# plot comparison of top origin countries and destination states
individuals %>%
  filter(country %in% top_ctrys,
         state_name %in% top_states) %>%
ggplot(aes(y = factor(country, rev(top_ctrys)), 
           fill = state_abb)) +
  geom_bar(position = "fill") + # normalize bar height
  theme(axis.text.x=element_blank(),
        legend.text = element_text(size=10),
        legend.position = "top",
        legend.justification = 0,
        legend.spacing.x = unit(.5, 'cm')) +
  labs(title = "Popular destination states by origin country", 
       y = element_blank(), 
       x = element_blank(), 
       fill = element_blank()) +
  guides(fill = guide_legend(nrow = 1, reverse = TRUE, 
                             label.position = "top")) +
  scale_fill_viridis_d()

```

```{r destmap, echo=FALSE}
# plot data on U.S. map with descriptive labels
plot_usmap(data = destinations, 
           values = "n") +
  theme(legend.position = "right") +
  scale_fill_continuous(name = "Guests",
                        low = "white", 
                        high = "darkgreen") +
  geom_label_repel(data = map_destinations, 
                   max.overlaps = 21,
                   aes(x = x,
                       y = y,
                       label = paste(abbr, comma(n, accuracy=1))),
            size = 3) +
  labs(title = "Destinations of Casa Alitas guests")

```

```{r desttl, echo=FALSE}
# vector with top (12) destination states
popular_dests <- destinations$state[destinations$n>150]

individuals %>% 
  filter(state_name %in% popular_dests) %>%
  ggplot(aes(x = arrival_date, 
             y = factor(state_name, rev(popular_dests)))) +
  geom_point(alpha = .2, na.rm = TRUE) +
  labs(title = "Arrivals over time by destination state",
       x = element_blank(), 
       y = element_blank()) +
  scale_x_date(date_breaks = "1 month", 
               date_labels = "%b",
               expand = c(.02,-.02))
```


### Further Resources



